### ISSUE TITLE
いい感じの各種アイコンを用意する

### ISSUE THREAD

**Issue by kakkokari-gtyih** [aiscript-dev/aiscript-vscode#1]
@syuilo さんにうまいことやってもらいたい（）

ファイルアイコン（任意の色、単色）
![image](https://github.com/aiscript-dev/aiscript-vscode/assets/67428053/b57ad0e7-fd17-4110-b835-45ced96bdd77)

拡張機能アイコン
![image](https://github.com/aiscript-dev/aiscript-vscode/assets/67428053/64600077-0afc-491f-9e71-d0d96f604859)

**Comment by syuilo** [comment]
👍

**Comment by syuilo** [comment]
Off topic: 拡張子 ais に変えたくなってきた

**Comment by kakkokari-gtyih** [comment]
👀👀👀

**Comment by syuilo** [comment]
意外とめんどくさそうで進んでない
